apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculatrice-front
  labels:
    app: calculatrice-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: calculatrice-front
  template:
    metadata:
      labels:
        app: calculatrice-front
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
        - name: calculatrice-front
          image: dlgart/calculatrice-front:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: calculatrice-front
  labels:
    app: calculatrice-front
spec:
  type: LoadBalancer
  selector:
    app: calculatrice-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
